# Generated by Django 2.0.4 on 2018-05-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_tracker', '0002_auto_20180420_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='attandance',
            name='total_time',
            field=models.IntegerField(default=0),
        ),
    ]
