# Generated by Django 2.0.4 on 2018-05-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_tracker', '0003_attandance_total_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attandance',
            name='total_time',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19),
        ),
    ]
