# Generated by Django 2.0.4 on 2018-05-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('SK', 'Sick Leave'), ('CA', 'Causal Leave')], default='SK', max_length=3)),
                ('leave_reason', models.TextField()),
            ],
        ),
    ]
