# Generated by Django 2.0.4 on 2018-05-17 14:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('leave_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='date_from',
            field=models.DateField(default=datetime.datetime(2018, 5, 17, 14, 19, 20, 808931, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='leave',
            name='date_to',
            field=models.DateField(default=datetime.datetime(2018, 5, 17, 14, 19, 20, 808951, tzinfo=utc)),
        ),
    ]
