# Generated by Django 2.0.4 on 2018-05-19 06:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leave_tracker', '0002_auto_20180517_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('CANCELED', 'Canceled')], default='PENDING', max_length=15),
        ),
        migrations.AlterField(
            model_name='leave',
            name='date_from',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='leave',
            name='date_to',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
