# Generated by Django 2.0.4 on 2018-05-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_tracker', '0003_auto_20180519_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('total_leave', models.IntegerField(default=0)),
            ],
        ),
    ]
