# Generated by Django 2.0.4 on 2018-05-28 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave_tracker', '0004_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leave_tracker.Season')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='users',
            field=models.ManyToManyField(through='leave_tracker.UserSeason', to=settings.AUTH_USER_MODEL),
        ),
    ]
