# Generated by Django 2.0.4 on 2018-05-29 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave_tracker', '0005_auto_20180528_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='user_season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leave_tracker.UserSeason'),
            preserve_default=False,
        ),
    ]
