# Generated by Django 2.0.4 on 2018-04-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attandance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('enter_at', models.DateTimeField()),
                ('out_at', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
